build: false

environment:
    CONAN_REFERENCE: "dlib/19.16.0"
    CONAN_USERNAME: "a-alaa"
    CONAN_LOGIN_USERNAME: "a-alaa"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/a-alaa/public-conan"

    matrix:
      - PYTHON: "C:\\Python27"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      - PYTHON: "C:\\Python35"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


install:
  - .ci/appveyor/install.bat

test_script:
  - .ci/appveyor/run.bat
